"""Add otp_purpose

Revision ID: 23feec37ce4f
Revises: 9aaf7574e4df
Create Date: 2026-08-24 14:27:25.516764

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '23feec37ce4f'
down_revision: str | Sequence[str] | None = '9aaf7574e4df'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_verifications', sa.Column('otp_purpose', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_verifications', 'otp_purpose')
    # ### end Alembic commands ###
