"""Add CartItem model

Revision ID: 6b318a05ffdb
Revises: 23feec37ce4f
Create Date: 2026-08-24 17:40:43.775642

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '6b318a05ffdb'
down_revision: str | Sequence[str] | None = '23feec37ce4f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
