"""add indexes to razorpay payment/order id

Revision ID: 6e7484db6b01
Revises: fdc0e9c76c42
Create Date: 2026-08-26 18:14:53.948026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e7484db6b01'
down_revision: Union[str, Sequence[str], None] = 'fdc0e9c76c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_orders_razorpay_order_id'), 'orders', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_orders_razorpay_payment_id'), 'orders', ['razorpay_payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_razorpay_payment_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_razorpay_order_id'), table_name='orders')
    # ### end Alembic commands ###
