"""Initial schema

Revision ID: 9aaf7574e4df
Revises: 
Create Date: 2026-08-24 13:32:29.702751

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '9aaf7574e4df'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
