"""Add cascade delete to Wishlist and CartItem product_id

Revision ID: fdc0e9c76c42
Revises: 4fb9b4c39ae0
Create Date: 2026-08-26 09:03:00.636617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdc0e9c76c42'
down_revision: Union[str, Sequence[str], None] = '4fb9b4c39ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_2'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_2'), 'wishlist', type_='foreignkey')
    op.create_foreign_key(None, 'wishlist', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlist', type_='foreignkey')
    op.create_foreign_key(op.f('fk_2'), 'wishlist', 'products', ['product_id'], ['id'])
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('fk_2'), 'cart_items', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
